Feature/publish release (#152)
* Publishing to Github wiki

* Fix repo ref + temp changes for testing

* temp change for testing

* temp change for passing pipeline

* temp change for passing pipeline

* temp change for running publish step

* Reverted temp changes

* Fixed typo

diff --git a/.github/workflows/cicd-2-publish.yaml b/.github/workflows/cicd-2-publish.yaml
--- a/.github/workflows/cicd-2-publish.yaml
+++ b/.github/workflows/cicd-2-publish.yaml
@@ -49,11 +49,36 @@ jobs:
     if: github.event.pull_request.merged == true
     timeout-minutes: 3
     env:
+      release_tag: ""
       version_bump: "PATCH"
     steps:
       - name: "Checkout code"
         uses: actions/checkout@v4
       - name: "Bump patch version"
+        id: "bump-patch-version"
         uses: ./.github/actions/versioning
         with:
+          release_tag: ${{ env.release_tag }}
           version_bump: ${{ env.version_bump }}
+      - name: "Checkout wiki"
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ github.repository }}.wiki
+      - if: ${{ env.release_tag == '' }}
+        run: |
+          echo "Error: The current release tag has not been found"
+          exit 1
+      - name: Create Release Notes
+        run: |
+          echo "Using following tag to create markdown file: ${{ env.release_tag }}"
+          echo "${{ github.event.pull_request.body }}" >> "v${{ env.release_tag }}.md"
+          echo "- [v${{ env.release_tag }}](https://github.com/NHSDigital/Galleri-Frontend/wiki/v${{ env.release_tag }})" >> Home.md
+      - name: Push to wiki
+        run: |
+          git config user.email "action@github.com"
+          git config user.name "GitHub Action"
+          git add .
+          git commit -m "docs: Added ${{ env.release_tag }} release file to wiki"
+          git push
+      - name: "Checkout code"
+        uses: actions/checkout@v4
